envs:
  - name: Sokoban
    n_envs: 32
    data_source: sokoban
    seed: [1, 32, 1]
    max_turns: 5
    response_length_per_turn: 512
    config:
      render_mode: vision
      min_solution_steps: [1,5]
